package SuccessfulTests;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.Map;

public class Project {

  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void clickProject() {
    driver.get("https://scodein.tech/project.html");
    driver.manage().window().maximize();
//    driver.findElement(By.className("githubLink"));
    driver.findElement(By.xpath("//*[@id=\"services\"]/div/div/div[2]/div[1]/h5/a")).click();
    String newUrl = driver.getWindowHandle();       //getting url of new page after click
    driver.switchTo().window(newUrl);
    String title = driver.getTitle();
    System.out.println("new title is: " + title );




  }
}
