package SuccessfulTests;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.Map;
public class SponsorFormTest {

  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void sponsorForm() throws InterruptedException {
    driver.get("https://scodein.tech/");
    driver.manage().window().maximize();
    driver.findElement(By.cssSelector(".main-nav li:nth-child(4) > a")).click();
    js.executeScript("window.scrollTo(0,102)");
    driver.findElement(By.cssSelector(".btn-lg")).click();
    String newUrl = driver.getWindowHandle();       //getting url of new page after click
    driver.switchTo().window(newUrl);               //switching to new page

  }
}
