package SuccessfulTests;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.Map;

public class WebinarSearchTest {

  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;


  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void WebinarSearchBar() {
    driver.get("https://scodein.tech/webinar.html");
    driver.manage().window().maximize();
    driver.findElement(By.id("txtSearch")).click();
    driver.findElement(By.id("txtSearch")).sendKeys("How to");
  }
}
